# Uncomment the next line to define a global platform for your project

source 'https://github.com/TuyaInc/TYPublicSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '9.0'

target 'TuyaSmartHomeKit_Example' do
  # Comment the next line if you don't want to use dynamic frameworks

pod 'TuyaSmartHomeKit','~>3.17.0'

pod 'TuyaSmartCameraKit', '~>4.17.1'
pod 'TuyaSmartCameraT', '~>4.17.6'
pod 'TYCameraCloudServicePanelSDK', '~>0.2.1'

pod 'TuyaSmartSecurityBaseKit', '~>2.1.0'
pod 'TuyaSmartSecurityBizAopKit', '~>2.1.0'
pod 'TuyaSmartSecurityServiceKit', '~>2.1.0'




pod 'TuyaSmartLogger'
  
pod 'MBProgressHUD', '~> 0.9.2'
pod 'BlocksKit'
pod 'SDWebImage'
pod 'Reachability'
pod 'Masonry'

  # Pods for TuyaSmartHomeKit_Example

end
